# Generated by Django 5.0 on 2023-12-24 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='video',
        ),
        migrations.RemoveField(
            model_name='blogtranslation',
            name='description',
        ),
    ]
