# Generated by Django 5.0 on 2024-01-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_blog_video_remove_blogtranslation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=12, max_length=30, verbose_name='телефон'),
            preserve_default=False,
        ),
    ]
